WITH
  datatemp AS (
    SELECT
      doi,
      year,
      is_oa,
      gold,
      green,
      temp_field.DisplayName as field,
      CitingInstitutions_count_uniq,
      CitingInstitutions_GiniSim,
      CitingInstitutions_Shannon,
      CitingCountries_count_uniq,
      CitingCountries_GiniSim,
      CitingCountries_Shannon,
      CitingSubregions_count_uniq,
      CitingSubregions_GiniSim,
      CitingSubregions_Shannon,
      CitingRegions_count_uniq,
      CitingRegions_GiniSim,
      CitingRegions_Shannon,
      CitingFields_count_uniq,
      CitingFields_GiniSim,
      CitingFields_Shannon,
      PERCENTILE_CONT(CitingInstitutions_count_uniq,0.5) OVER(PARTITION BY temp_field.DisplayName, year, is_oa, gold, green) AS CitingInstitutions_count_uniq_perc50,
      PERCENTILE_CONT(CitingInstitutions_GiniSim,0.5) OVER(PARTITION BY temp_field.DisplayName, year, is_oa, gold, green) AS CitingInstitutions_GiniSim_perc50,
      PERCENTILE_CONT(CitingInstitutions_Shannon,0.5) OVER(PARTITION BY temp_field.DisplayName, year, is_oa, gold, green) AS CitingInstitutions_Shannon_perc50,
      PERCENTILE_CONT(CitingCountries_count_uniq,0.5) OVER(PARTITION BY temp_field.DisplayName, year, is_oa, gold, green) AS CitingCountries_count_uniq_perc50,
      PERCENTILE_CONT(CitingCountries_GiniSim,0.5) OVER(PARTITION BY temp_field.DisplayName, year, is_oa, gold, green) AS CitingCountries_GiniSim_perc50,
      PERCENTILE_CONT(CitingCountries_Shannon,0.5) OVER(PARTITION BY temp_field.DisplayName, year, is_oa, gold, green) AS CitingCountries_Shannon_perc50,
      PERCENTILE_CONT(CitingSubregions_count_uniq,0.5) OVER(PARTITION BY temp_field.DisplayName, year, is_oa, gold, green) AS CitingSubregions_count_uniq_perc50,
      PERCENTILE_CONT(CitingSubregions_GiniSim,0.5) OVER(PARTITION BY temp_field.DisplayName, year, is_oa, gold, green) AS CitingSubregions_GiniSim_perc50,
      PERCENTILE_CONT(CitingSubregions_Shannon,0.5) OVER(PARTITION BY temp_field.DisplayName, year, is_oa, gold, green) AS CitingSubregions_Shannon_perc50,
      PERCENTILE_CONT(CitingRegions_count_uniq,0.5) OVER(PARTITION BY temp_field.DisplayName, year, is_oa, gold, green) AS CitingRegions_count_uniq_perc50,
      PERCENTILE_CONT(CitingRegions_GiniSim,0.5) OVER(PARTITION BY temp_field.DisplayName, year, is_oa, gold, green) AS CitingRegions_GiniSim_perc50,
      PERCENTILE_CONT(CitingRegions_Shannon,0.5) OVER(PARTITION BY temp_field.DisplayName, year, is_oa, gold, green) AS CitingRegions_Shannon_perc50,
      PERCENTILE_CONT(CitingFields_count_uniq,0.5) OVER(PARTITION BY temp_field.DisplayName, year, is_oa, gold, green) AS CitingFields_count_uniq_perc50,
      PERCENTILE_CONT(CitingFields_GiniSim,0.5) OVER(PARTITION BY temp_field.DisplayName, year, is_oa, gold, green) AS CitingFields_GiniSim_perc50,
      PERCENTILE_CONT(CitingFields_Shannon,0.5) OVER(PARTITION BY temp_field.DisplayName, year, is_oa, gold, green) AS CitingFields_Shannon_perc50
    FROM `coki-scratch-space.citation_diversity_analysis.citation_diversity_global`, UNNEST(fields) AS temp_field
    WHERE (CitationCount >= 2) AND (is_oa IS NOT NULL)
  )
SELECT
  field,
  year,
  is_oa,
  gold,
  green,
  ANY_VALUE(CitingInstitutions_count_uniq_perc50) AS CitingInstitutions_count_uniq_median,
  AVG(CitingInstitutions_count_uniq) AS CitingInstitutions_count_uniq_mean,
  ANY_VALUE(CitingInstitutions_GiniSim_perc50)AS CitingInstitutions_GiniSim_median,
  AVG(CitingInstitutions_GiniSim) AS CitingInstitutions_GiniSim_mean,
  ANY_VALUE(CitingInstitutions_Shannon_perc50) AS CitingInstitutions_Shannon_median,
  AVG(CitingInstitutions_Shannon) AS CitingInstitutions_Shannon_mean,
  ANY_VALUE(CitingCountries_count_uniq_perc50) AS CitingCountries_count_uniq_median,
  AVG(CitingCountries_count_uniq) AS CitingCountries_count_uniq_mean,
  ANY_VALUE(CitingCountries_GiniSim_perc50)AS CitingCountries_GiniSim_median,
  AVG(CitingCountries_GiniSim) AS CitingCountries_GiniSim_mean,
  ANY_VALUE(CitingCountries_Shannon_perc50) AS CitingCountries_Shannon_median,
  AVG(CitingCountries_Shannon) AS CitingCountries_Shannon_mean,
  ANY_VALUE(CitingSubregions_count_uniq_perc50) AS CitingSubregions_count_uniq_median,
  AVG(CitingSubregions_count_uniq) AS CitingSubregions_count_uniq_mean,
  ANY_VALUE(CitingSubregions_GiniSim_perc50)AS CitingSubregions_GiniSim_median,
  AVG(CitingSubregions_GiniSim) AS CitingSubregions_GiniSim_mean,
  ANY_VALUE(CitingSubregions_Shannon_perc50) AS CitingSubregions_Shannon_median,
  AVG(CitingSubregions_Shannon) AS CitingSubregions_Shannon_mean,
  ANY_VALUE(CitingRegions_count_uniq_perc50) AS CitingRegions_count_uniq_median,
  AVG(CitingRegions_count_uniq) AS CitingRegions_count_uniq_mean,
  ANY_VALUE(CitingRegions_GiniSim_perc50)AS CitingRegions_GiniSim_median,
  AVG(CitingRegions_GiniSim) AS CitingRegions_GiniSim_mean,
  ANY_VALUE(CitingRegions_Shannon_perc50) AS CitingRegions_Shannon_median,
  AVG(CitingRegions_Shannon) AS CitingRegions_Shannon_mean,
  ANY_VALUE(CitingFields_count_uniq_perc50) AS CitingFields_count_uniq_median,
  AVG(CitingFields_count_uniq) AS CitingFields_count_uniq_mean,
  ANY_VALUE(CitingFields_GiniSim_perc50)AS CitingFields_GiniSim_median,
  AVG(CitingFields_GiniSim) AS CitingFields_GiniSim_mean,
  ANY_VALUE(CitingFields_Shannon_perc50) AS CitingFields_Shannon_median,
  AVG(CitingFields_Shannon) AS CitingFields_Shannon_mean
FROM datatemp
GROUP BY field, year, is_oa, gold, green
ORDER BY field, year, is_oa, gold, green